---
title: "Homework 2"
author: "Yuki Joyama"
date: "2023-09-26"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T)
```

# Problem 1
```{r, echo=F, message=F}
library(tidyverse)
```

Import and clean the data in pols-month.csv

```{r}
pols_month_df =
  read_csv("./fivethirtyeight_datasets/pols-month.csv") |> # import pols_month.csv file
  separate(col=mon, into=c("year", "month", "day")) |> # separate mon variable into year, month and day
  mutate(
    year = as.integer(year), # change the class of year, month, day to integer
    month = as.integer(month),
    day = as.integer(day),
    month = case_match(
    month,
    01 ~ "jan",
    02 ~ "feb",
    03 ~ "mar",
    04 ~ "apr",
    05 ~ "may",
    06 ~ "jun",
    07 ~ "jul",
    08 ~ "aug",
    09 ~ "sep",
    10 ~ "oct",
    11 ~ "nov",
    12 ~ "dec"
    ), # replace month number with month name
    president = case_when(
      prez_gop == 1 ~ "gop",
      prez_dem == 1 ~ "dem"
    ) # make a new variable president with values gop and dem
  ) |> 
  select(-c("prez_dem", "prez_gop", "day")) # remove prez_dem, prez_gop, and day

pols_month_df
```

Import and clean the data in snp.csv

```{r}
snp_df =
  read_csv("./fivethirtyeight_datasets/snp.csv") |> # import snp.csv file
  separate(col = date, into = c("month", "day", "year")) |> # separate date variable into year, month and day
  mutate(
    year = as.integer(year), # change the class of year, month, day to integer
    month = as.integer(month),
    day = as.integer(day),
    year = case_when(
      year < 23 ~ 2000 + year,
      year >=23 ~ 1900 + year
    ) # if year < 23, add 2000; if year >= 23, add 1900
  ) |> 
  arrange(year, month) |> # arrange order according to year and month
  mutate(
    month = case_match(
    month,
    01 ~ "jan",
    02 ~ "feb",
    03 ~ "mar",
    04 ~ "apr",
    05 ~ "may",
    06 ~ "jun",
    07 ~ "jul",
    08 ~ "aug",
    09 ~ "sep",
    10 ~ "oct",
    11 ~ "nov",
    12 ~ "dec"
    ) # replace month number with month name
  ) |> 
  relocate(year, month) |> # change position of columns year and month
  select(-"day") # remove day

snp_df
```

Import and clean the data in unemployment.csv

```{r}
unemployment_df =
  read_csv("./fivethirtyeight_datasets/unemployment.csv") |> # import unemployment.csv file
  janitor::clean_names() |> # clean the variables name
  pivot_longer(
    cols = c("jan","feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"),
    names_to = "month",
    values_to = "unemployment_rate"
  ) # change the dataset from wide to long

unemployment_df
```

Now, let's merge snp into pols, and merge unemployment data into the result.

```{r}
fivethrityeight_df =
  left_join(pols_month_df, snp_df, by = c("year", "month")) |> # merge snp into pols,
  left_join(unemployment_df, by = c("year", "month")) |> # merge unemployment data into the result
  relocate("year", "month", "president", "close", "unemployment_rate") # bring key variables to the front

fivethrityeight_df
```



